
version: 2

models:
    - name: ae_ad_network_1_campaign_updates
      description: "Campaign history report from Ad Network 1"
      columns:
          - name: campaign_id
            description: "ID of a marketing campaign from Ad Network 1"
            tests:
                - not_null
          - name: update_date
            description: "Date when the campaign info was updated"
            tests:
                - not_null
          - name: name
            description: "Name of the campaign"
            tests:
                - not_null
    - name: ae_ad_network_1_geo_dictionary
      description: "Geo dictionary for Ad Network 1"
      columns:
          - name: id
            description: "ID of a marketing campaign from Ad Network 1"
          - name: country_code
            description: "Alpha-2 code of a country"
          - name: name
            description: "Full name of the location"
          - name: location_type
            description: "Type of the location"
    - name: ae_ad_network_1_country_report
      description: "Country-level performance report of Ad Network 1"
      columns:
          - name: date
            description: "Date"
            tests:
                - not_null
          - name: campaign_id 
            description: "ID of a marketing campaign from Ad Network 1"
            tests:
                - not_null
          - name: country_id
            description: "ID of a location (country)"
            tests:
                - not_null
          - name: spend
            description: "Ad spend"
            tests:
                - not_null
          - name: impressions
            description: "# Impressions of the ads"
            tests:
                - not_null
          - name: clicks
            description: "# Clicks on the ads"
            tests:
                - not_null
    - name: ae_ad_network_1_detailed_report
      description: "State-level performance report of Ad Network 1 when applicable"
      columns:
          - name: date 
            description: "Date"
            tests:
                - not_null
          - name: campaign_id 
            description: "ID of a marketing campaign from Ad Network 1"
            tests:
                - not_null
          - name: country_id
            description: "ID of a location (country)"
            tests:
                - not_null
          - name: state_id
            description: "ID of a location (state)"
            tests:
                - not_null
          - name: spend
            description: "Ad spend"
            tests:
                - not_null
          - name: impressions
            description: "# Impressions of the ads"
            tests:
                - not_null
          - name: clicks
            description: "# Clicks on the ads"
            tests:
                - not_null
    - name: ae_ad_network_2_report
      description: "Performance report of Ad Network 2"
      columns:
          - name: id
            description: "ID of a marketing campaign from Ad Network 2"
            tests:
                - not_null
          - name: campaign_name
            description: "Name of a marketing campaign from Ad Network 2"
            tests:
                - not_null
          - name: date 
            description: "Date"
            tests:
                - not_null
          - name: spend
            description: "Ad spend"
            tests:
                - not_null
          - name: impressions
            description: "# Impressions of the ads"
            tests:
                - not_null
          - name: clicks
            description: "# Clicks on the ads"
            tests:
                - not_null
    - name: dim_geo_network_1_detailed_report
      description: "Network 1 Detailed report with extra geo information from geo dictionary" 
      columns:
          - name: date 
            description: "Date"
          - name: campaign_id 
            description: "ID of a marketing campaign from Ad Network 1"
          - name: country_id
            description: "ID of a location (country)"
          - name: state_id
            description: "ID of a location (state)"
            tests:
                - not_null
          - name: spend
            description: "Ad spend"
          - name: impressions
            description: "# Impressions of the ads"
          - name: clicks
            description: "# Clicks on the ads"
          - name: state_name
            description: "Full name of the state"
            tests:
                - not_null
          - name: country_name
            description: "Full name of the country"
            tests:
                - not_null
          - name: country_code
            description: "Alpha-2 code of a country"
            tests:
                - not_null
    - name: dim_geo_network_1_country_report
      description: "Network 1 country report with extra geo information from geo dictionary"
      columns:
          - name: date
            description: "Date"
          - name: campaign_id 
            description: "ID of a marketing campaign from Ad Network 1"
          - name: country_id
            description: "ID of a location (country)"
          - name: spend
            description: "Ad spend"
          - name: impressions
            description: "# Impressions of the ads"
          - name: clicks
            description: "# Clicks on the ads"
          - name: country_name
            description: "Name of the country"
          - name: country_code
            description: "Alpha-2 code of a country"    
    - name: network_1_unique_campaign_ids
      description: "Unique campaign_id list for Ad Network 1"
      columns:
          - name: campaign_id
            description: "ID of a marketing campaign from Ad Network 1"
            tests:
                - not_null
                - unique
    - name: network_1_final_model
      columns:
          - name: campaign_id,
          - name: update_date,
          - name: campaign_name,
          - name: detailed_report_date,
          - name: country_id,
          - name: state_id,
          - name: state_name,
          - name: country_name,
          - name: country_code,
          - name: detailed_report_spend,
          - name: detailed_report_impressions,
          - name: detailed_report_clicks,
          - name: country_report_date,
          - name: country_report_spend,
          - name: country_report_impressions,
          - name: country_report_clicks
    - name: networks_unified_datamart
      columns:
          - name: network_type
          - name: campaign_id
          - name: n2_date
          - name: n1_update_date
          - name: campaign_name
          - name: n2_spend
          - name: n2_impressions
          - name: n2_clicks
          - name: n1_country_id
          - name: n1_state_id
          - name: n1_state_name
          - name: n1_country_name
          - name: n1_country_code
          - name: n1_detailed_report_date
          - name: n1_detailed_report_spend
          - name: n1_detailed_report_impressions
          - name: n1_detailed_report_clicks
          - name: n1_country_report_date
          - name: n1_country_report_spend
          - name: n1_country_report_impressions
          - name: n1_country_report_clicks
                    